language: node_js
node_js:
- 5.4.1
cache:
  directories:
  - node_modules
env:
  global:
  - secure: tyWdtKMq6JCN3qdIA1Q3ShJcno2LE7nOiSSUcsZNQj3reqVnU4MNgp2cXjZryM2QffPMy8WJuIZ6Yoi1BFNCd5E9n91WWVQkydWwQCbNuSNuhupzqvjjqPibq0iKx7q7GU7EaXlotlSsLiOCVQCjZe0FQ8R2zAegSeWEy2FEa5YDeYSSTTeFJFfVCzQDxhKz6NUatpwXHvREhK1MMbxj/THTAdVibWWFb0gPrXx5r6J+itj9Gk/XEzCgS1Vq83114dIzLiDpH4GXtk+pqAAM41fyt6OPhGCxALcGk9wZpMEazU61CDDGSZPqDK9/dJ+laN49vvjL+q4ol/QwVwW4GDc7z6fvyb34UHQb9ZU7tvTA5FpWM08ECR63BAlWQUYzr70OstjpMHghjFP/8Os3Ph9HibhiIrN62XmJ0gOoPdja3CUgAfLqRfm4gu4nH84cxphQI86462XcmsniizCBcIRqr9AMWw4btfa4SXPWNM2HC/qsav165J/xHZqjfJgPcTHZH4OAIV6ewfhICK2lT8+dvNfwGERr7PcgXnabKOm6V7tUzE4CKI3hE9gDyZhOOTpXIQYZq++BApVzBwuuheOPyZb5XoP3FWOFxRpn4upZzvhI8XPBlYA0ajfk36lsfUjDD8L5Yp0BtxwnlKiN2f6lkb52eu2Sn/Yq1SSZLqo=
  - secure: P908PjQSZNco84tDp4AeCupf8PLyV696XBwEkWS3HgS+LIkn7Mp7rLAjwiacnmjCaXs/IgwjL4qZ0uGsqd7ff+1JkOwWp60SPySQ6HAsgLa0uN2oZZMRsjnXwH2jU67eiUrfsOoOtYJvd6fmj4nSjDXZSA9b0v81Mi71NfVEyXSyAN3rPFutzhwlNrJkI2AwsdFPmMx/9vhrBJP4InyewcR2cmHc5eQEfI6/2lQB+p9nVcs3fVjCLVf1M2sl8CyRBZHel5wY+b8GL8K8i8WvuPm45i+dPaTtAYuB/llEmYS9jJkawlDwV+e8yXhQ8Qgoy5X64794Ixxlb9cEjCzzbL15/Ob57bn4h46357vc82eHAwD6HH2lXsLuSYsDHrbFgDrIPLAbA1bpqU9iEJCWLyZx3m1mqbYOV/+mkvk1GxHJUN+Gqo6vBwdKPaAuQJpD7JCIIgzVnpROJxllNVMvq35xOYFyBj+31Rjk7rpfbUkOaqh7CqSZZ4ylwvF0N/I8Moj2P37eceB1YRvD1M8QCo+z6ZXNtTZjtF8/pL6+EZ8mALNqAj71MYhW1KFYJAnftKhaMV94ZwOzXda6fcJ+AYNF1PUa1VAoOLtRV40EAiu8/NKlLXxPFbFHueoM2o4smUYsmih9ifBAn5kzH4xn/dUfeEDeH7DEz5M35WpzfGM=
before_script:
- npm install -g bower
- npm install -g gulp
- npm install
- bower install
- gulp build:prod
after_success:
  gulp deploy --user $FTP_FISCHER_USER --password $FTP_FISCHER_PASSWORD
