language: node_js
node_js:
- 5.4.1
cache:
  directories:
  - node_modules
env:
  global:
  - secure: JsH+9zUbFjuhE/QrUAf4e0GaRsPk8eVGFqcmdGgatokR588Sa8cLHe+FNE/dFY+h8DcVXhe2AMl8kboNZ+cf74GmO5feGfzlQesUpdKTXhnB5U5TBgl8yHOYzE6vxOpUVGDMM2zb+T43GGRq0UmlPx1KMi6V3dZ+8oLEjUN0PHe2hU3D8bBqjd3bI/l4YCj/tCvijLhIAMN5ohSd1QHZJDmyibmVC1m7cRnMveBVGTASyIT3HGDc/9mOnRiOJs0BSH96NMxIj/Nvc2ks5arRO58ag2saSJ8ZU1Uo5/7Cj6wxgttzuXAzEjsDy6qKTI+G9aUs1wZVJqFIZEnfnyu2xrZ4BgtDjnoD0hISbADpee4u2Vf4RAXLFo5bJINp0N1RytOhTtAb/z+6uCXqkAP+Ba5CnQnIZaPFCWiJvWKnFmpb1E+iCFlM2QqKObjrIM/bJS0uqTO6NZYsn8iCvt5YbogGV/ycY0/s7OLfOjHZ+b7pGk1zCjshQmZVV74eEg3ONe0GOhhj2Y0M42BuRQGXw7SBrZxjzojBb5CaTkEzfTBnMVFZ6xwXxQLZvkt/gXUB8Xfhq1CjMNc1uvIh3iKqx8hcAzHLi3jSbVq/61blXm0NHG4r0N1d0pCKPhR74VlpgLfQ3Be83qVnjVe1u3p32QDXW9c6BuhplHs7pTCtr8Q=
  - secure: jy/IcBCw0Q6d9FPftMh0z/I0WMj0YdQfC20KpF/zBtad/o5aKhYSV+escWKbgTGOGhmw/gOFPSlWlH/Sx7upPVS8VtFMgbm3H2XmXNw89rJcn6Y33t5tlVM8v+z97ycALw6lFAjtnAgeYcgBWB0bDUag7yOvoR/sIqGiinFp2cRib7GRzLnwoEuFuXqIJIi+6IPYsPU5gyvMQsI3CG7c8npt0uYW79a5y4TvzfeW/lqzq1rNANkfXcPBw3XKwITG31JiK0sPX/drs90WlMUZJoG8aE5ZAwdDy5+9ebU1eeeXOc3miuCgyCIm4DgiF218gHNEM2zu4yMM3AGnAqOA24Sz4N+JgtkUBV6SfDqtvzvHRZOotp/kGMrN+aEIoSJbvssVMPL4oj9/IwNgZSc4AfQjPZ2KmLRNAQe2+IGxRyo7dB/Kag/v/5IKjTWQtyiZmBlqNc5pt0bOQK4AaKgfApr3E6xX5rXuP7d6PJekywn3d9R5mMJzOt+yvOmp/haqtzw+i9RGiGc2xh5UG0B7/pySXMma+dIRD2EJ41jBCQp1O11bhISDjbu9PWDkwXAvwIX7DRK7dQ7qYRlZC5SCoIqJwm+Pc7RfYO5s1LeUw+SuSPi/Q532OMkAt7bfxKbYD5yGGI1IwIIDo9/gVzaFeSRtUq3JY0nvxYgvcRzh4wo=
before_script:
- npm install -g bower
- npm install -g gulp
- npm install
- bower install
- gulp build
after_success:
  gulp deploy --user $FTP_FISCHER_USER --password $FTP_FISCHER_PASSWORD
